/*
 * I Laboratorio Programado
 * Registro de Automóviles
 * 
 * Estudiante: Daniel Somarribas Quirós
 * Carné: b57072
 */
package Vista;

import Controlador.Controlador_RegistroAutomoviles;
import Modelo.Metodos_RegistroAutomoviles;

/**
 * @author sqdan
 */
public class JFRM_RegistroAutomoviles extends javax.swing.JFrame {
    Controlador_RegistroAutomoviles controlador;
    Metodos_RegistroAutomoviles metodos;
    
    /**
     * Crea el Frame Registro de Automóviles
     */
    public JFRM_RegistroAutomoviles() 
    {
        initComponents();
        controlador = new Controlador_RegistroAutomoviles(this);
        agregarEventos();
        estadoSinBuscar();
        estadoSinAgregar();
    }
    
    /*
    * Agregar los eventos a los botones
    */
    public void agregarEventos()
    {
        jpnl_Registro.agregarEventos(controlador);
        jpnl_Botones.agregarEventos(controlador);
    }
    
    public String getNumero()
    {
        return jpnl_Registro.getNumero();
    }
    
    public void setFields(String[] todo)
    {
        jpnl_Registro.setTodo(todo);
    }
    
    public String[] getFields()
    {
        return jpnl_Registro.getTodo();
    }
    
    public void setNumeroRegistro(String numeroRegistro)
    {        
        jpnl_Registro.setNumero(numeroRegistro);
    }
    
    public void clearFields()
    {
        jpnl_Registro.clearFields();
    }
    
    public void estadoBuscar()
    {
        jpnl_Botones.estadoBuscar();
    }
    
    public void estadoSinBuscar()
    {
        jpnl_Botones.estadoSinBuscar();
    }
    
    public void estadoSinAgregar()
    {
        jpnl_Registro.estadoSinAgregar();
    }
    
    public void estadoAgregar()
    {
        jpnl_Registro.estadoAgregar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl_Registro = new Vista.JPNL_Registro();
        jpnl_Botones = new Vista.JPNL_Botones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jpnl_Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnl_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnl_Registro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnl_Botones, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        //Look and Feel apesta >:(
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRM_RegistroAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRM_RegistroAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRM_RegistroAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRM_RegistroAutomoviles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRM_RegistroAutomoviles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.JPNL_Botones jpnl_Botones;
    private Vista.JPNL_Registro jpnl_Registro;
    // End of variables declaration//GEN-END:variables
}
